name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        profile:
          - dev
          - release
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.toolchain}}

    - name: Show version
      run: cargo version

    - name: Build
      run: cargo build --verbose --profile ${{matrix.profile}}

    - name: Run tests
      run: cargo test --verbose --profile ${{matrix.profile}}

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt

    - name: Check formatting
      run: cargo fmt --all --check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items