name: Miri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - mips-unknown-linux-gnu
          - mips64-unknown-linux-gnuabi64
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v3

    - name: Setup toolchain with Miri
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri

    - name: Run tests under Miri
      run: cargo +nightly miri test --verbose --target ${{matrix.platform}} --all-features
