name: Rust MIRI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MIRI
      run: |
        rustup toolchain add nightly
        rustup +nightly component add miri
    - name: Run tests under MIRI
      run: cargo +nightly miri test --verbose
